FROM openjdk

COPY sportsbetting-application-spring-app/target/sportsbetting-application-spring-app-1.0-SNAPSHOT-jar-with-dependencies.jar /deployments/

CMD java -jar /deployments/sportsbetting-application-spring-app-1.0-SNAPSHOT-jar-with-dependencies.jar
